#!/bin/bash

OPENSHIFT_INTERNAL_IP=127.0.0.1
OPENSHIFT_INTERNAL_PORT=8080
OPENSHIFT_DATA_DIR=/tmp/data

mkdir $OPENSHIFT_DATA_DIR

export OPENSHIFT_INTERNAL_IP=$OPENSHIFT_INTERNAL_IP
export OPENSHIFT_INTERNAL_PORT=$OPENSHIFT_INTERNAL_PORT
export OPENSHIFT_DATA_DIR=$OPENSHIFT_DATA_DIR


